### ISSUE TITLE
Not possible to convert images without extension

### ISSUE THREAD

**Issue by leonardofraga91** [vnbaaij/ImageProcessor.Web.Episerver#60] opened 2021-12-03 19:38 UTC
Hi guys, not sure if it is a bug or something expected. I'm creating a bug because I wasn't able to find any documentation about this.

I have a lot of images that have no extension (e.g. IMAGE_09 instead of IMAGE_09.png), and when I try to resize or change the format nothing happens, the image just keeps the same.

Example:
../image/picture01.png?width=440&format=webp -> this one works fine.
../image/picture01?width=440&format=webp -> this one doesn't works.

Do you guys, have a solution, documentation, or suggestions showing how to solve that?

**Comment by vnbaaij** [comment] 2021-12-03 19:57
Not a bug, but expected (and won't fix).
One of the first things done is to check if the request is valid. To do that the `ImageService` calls 
 `ImageHelpers.IsValidImageExtension(path);` which is a function from `ImageProcessor.Web`. As you can guess, this looks at the extension of an image to determine if the request is indeed for an image.

**Closed as completed by vnbaaij** 2021-12-03 19:57 UTC

**Comment by leonardofraga91** [comment] 2021-12-03 20:00
Thanks for your fast response and for all context!!!
